### ISSUE TITLE
It seems to be incompatible with lazierae2

### ISSUE THREAD

**Issue by vaiium** [AlmostReliable/merequester#18]
### Version

1.18.2

### Crash Report

[main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Unsupported installed optional dependencies:     Mod ID: 'lazierae2', Requested by: 'merequester', Expected range: '[INCOMPATIBLE,INCOMPATIBLE]', Actual version: '3.1.5'

### Additional Context

Yes

### Modifications

The server wont boot with this and lazyae2 installed. 

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by vaiium** [comment]
It seems weird. I see you updated to 1.20.1. But to be direct. Why would i use this without lazier ae2?

**Comment by rlnt** [comment]
I don't know what 1.20.1 has to do with your report and why you would bring that up. LazierAE2 only exists for 1.18 right now since I am still working on the update.

LazierAE2 itself has an ME Requester built into it. It's pretty much the origin of the Requester.
But as time moved on, people asked me to port ME Requester as a standalone mod because that was the only feature they needed. So I started working on the standalone Requester mod for 1.19 and backported it to 1.18 (mostly because of Fabric packs asking for it and LazierAE2 wasn't available for Fabric).

However, since LazierAE2 already has a Requester, it is incompatible with ME Requester 1.18 Forge because they share a lot of internals and tend to conflict with each other. So that's completely intentional. Just use the LazierAE2 requester.

**Comment by vaiium** [comment]
Sorry for any confusion. I didn't start off wanting to come across rude. But the regular requester from lazyae2 doesn't do fluids. So now i have to choose. Either the whole of lazyae2 but not fluid requesting. Or the separate me requester but then no lazy(ier)ae2.

**Comment by rlnt** [comment]
Sorry, nothing I can do about it. That's the sacrifice I had to make.

**Comment by vaiium** [comment]
Ah dang, the search continues. Thank you very much for your response!
