### ISSUE TITLE
[1.18.2] Compat issue with Lazier AE2

### ISSUE THREAD

**Issue by accessdenied0** [AlmostReliable/merequester#4]
### Version

1.18.2, Stoneblock 3, modified with ME-Requester / Lazier AE2

### Crash Report

https://gist.github.com/accessdenied0/7e83e43108dd7efc47f02941449e8988#file-gistfile1-txt

### Log

https://gist.github.com/accessdenied0/7e83e43108dd7efc47f02941449e8988#file-gistfile1-txt

### Additional Context

Yes

### Modifications

The issue seem to be an compat problem with LazierAE2... I first was looking into MineTogether but then found a part in the log which made me try to disable LazierAE2:
`net.minecraftforge.fml.ModLoadingException: Mod §emerequester§r only supports §3lazierae2§r §oINCOMPATIBLE§r
§7Currently, §3lazierae2§r§7 is §o3.1.4`

It seems that there is some sorts of Version Incompatibility per Requirement, but since both mods yours and the LazierME has only 1 version for 1.18.2, I can only disable one of them...

### Did the crash happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
I marked them as incompatible since Lazier AE2 adds the requester block itself. The ME Requester mod is not needed if you have Lazier AE2.

For future versions (1.19+), this will no longer be a thing as I completely decoupled the requester to its own mod and it will no longer be a part of Lazier AE2. However, I was asked to backport the Requester mod to 1.18 and since it was already present in my other addon, it's now marked as incompatible.

I recommend getting rid of the ME Requester mod if you want to use Lazier AE2. It has all the features built in. But if you don't need the extra stuff Lazier AE2 adds, remove it and only use the ME Requester mod. :)

**Comment by accessdenied0** [comment]
Oh yeah... my bad... I completely forgot LazierAE2 has an Requester by itself... but it seems that the Requester from your mod is much more flashed out... I apologize for this mistake... 

I guess was just a bit surprised, normally mods do not take that into account and add items double.
I would have probably just hid the item per script to use one of them other... (to use them in conjunction)
 
A bit off topic but...
One thing I am missing form LazyAE2 (the 1.12.2 original) is the Multi Block Crafting Unit... so I have to consider...

I thank you alot for your help!
