### ISSUE TITLE
MC 1.18.2 Fabric - Cannot see ME Requester in REI/Can't craft item

### ISSUE THREAD

**Issue by TheWyzer** [AlmostReliable/merequester#8]
### Version

1.18.2-1.02

### Describe the bug!

I am unable to search for, or find the ME Requester in either REI or in the ME Crafting Terminal.  I tried @me and even searching for request, no joy.

I am running the latest version of AE2, 11.7.0 with the "add-on" mods of AE2Things 1.1.1-beta.1, AE2WTLib 11.6.3 (Wireless Terminal Mod), and AE Additions 3.1.2-Fabric

If there is anything else that I can provide, I will be happy to try to do so.

Also your Discord invite has expired, as I did try to go there first.

### Additional Context

Yes

### Modifications

None.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Which Discord link do you use? We never changed the invite link since the creation of the server so everything should be up-to-date. The GitHub readme has the right one as well as the CurseForge site. Where is that invalid link located?

I also can't reproduce that issue. It's a normal crafting recipe and doesn't have any special integration in order to be shown.
![](https://i.imgur.com/3W81GP9.png)
![](https://i.imgur.com/wTWC523.png)

Maybe you installed the Forge version accidentally instead of the Fabric version. I need to see your log in order to help you.

**Comment by TheWyzer** [comment]
Thank you for the response.

This link code, https://discord.com/invite/ThFnwZCyYY, which is on this Github page, and Curseforge page for this mod.

Here is a link to my mod list, https://pastebin.com/WJ1tALmy  taken from the MultiMC loading log, so it is "launching" at load up, but is not shown in the in-game mod list.  I don't have anything set to hidden either.



<blockquote><img src="https://cdn.discordapp.com/icons/917251858974789693/a_5e06685d71cbebe8fec7a1d149bcea17.jpg?size=256" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/invite/ThFnwZCyYY">Join the Almost Reliable Discord Server!</a></strong></div><div>The official support and community server of Team Almost Reliable. | 247 members</div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/WJ1tALmy">MC 1.18.2 Mod List of Custom Pack - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rlnt** [comment]
That link is valid and the only one that exists for the server.

And this is not the log I need. You have to upload your `latest.log` from your logs folder.

**Comment by TheWyzer** [comment]
[latest.log](https://github.com/AlmostReliable/merequester/files/10203076/latest.log)

That is strange, as each time I click the link it states it is "invalid".

**Comment by rlnt** [comment]
Your log doesn't mention ME Requester at all. I am pretty sure you installed the Forge version instead of the Fabric version. The files are hosted under the same project.

Please use this one https://www.curseforge.com/minecraft/mc-mods/merequester/files/4094405

<blockquote><div><strong><a href="https://www.curseforge.com/minecraft/mc-mods/merequester/files/4094405">Just a moment...</a></strong></div></blockquote>

**Comment by TheWyzer** [comment]
OK, I downloaded it twice, and I am sure I had the fabric one.  Used your link, overwrote the file and now it works.  Thank you very much for your time and help.

Also, since I cannot get the link to work, I tried 2 other browsers and even the app itself, with no luck.  Can you please send me an invite, REDACTED

Thank you again.
